package webservice.bean;

import java.util.Date;

/**
 * Customer generated by MyEclipse Persistence Tools
 */

public class Customer implements java.io.Serializable {

	// Fields

	private String custId;

	private String custName;

	private String address;

	private String cellphone;
	private String decOrderId;
	

	// Constructors

	/** default constructor */
	public Customer() {
	}

	/** minimal constructor */

	

	// Property accessors

	public String getCustId() {
		return this.custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getDecOrderId() {
		return this.decOrderId;
	}

	public void setDecOrderId(String decOrderId) {
		this.decOrderId = decOrderId;
	}

	
}