
package webservice.bean;

import java.util.Date;
//import webservice.bean.Customer;
/**
 * Customer generated by MyEclipse Persistence Tools
 */

public class PayPlan implements java.io.Serializable {

	// Fields


	
	private String id;//收款序号
	private String contractId  ;  //合同编号
	private Double amont;// 收款金额
	private Date payTime;// 收款日期
	//private String payType;// 付款方式
	//private String billNo;// 票据编号
	private String payForUse;// 款项用途
	private String remark;// 备注信息
	private String person;// 录入人
	private Date time;// 录入时间

	// Constructors

	/** default constructor */
	public PayPlan() {
	}

	

	

	// Property accessors
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	public String getContractId() {
		return this.contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	public Date getPayTime() {
		return this.payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	
	public String getPayForUse() {
		return this.payForUse;
	}

	public void setPayForUse(String payForUse) {
		this.payForUse = payForUse;
	}
	

	public Double getAmont() {
		return this.amont;
	}

	public void setAmont(Double amont) {
		this.amont = amont;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}
	
}