package webservice.bean;

import java.util.Date;
//import webservice.bean.Customer;
/**
 * Customer generated by MyEclipse Persistence Tools
 */

public class MtrRequest implements java.io.Serializable {

	// Fields
	long mrqId;//要货编号
	String contractId;  //订单编号
	Date planDate ;// 要货日期
	Date delvDate ;// 要求交付日期
	String reqUser;// 要货人员
	String contactUser;// 联系人员
	String contactPhone;//联系电话
	String delvAddr;	//送货地址
	String remark;	//要货描述
	MtrRequestDetail[] mrds;	//要货明细

	// Constructors

	/** default constructor */
	public MtrRequest() {
	}


	// Property accessors

	public Long getMrqId() {
		return this.mrqId;
	}

	public void setMrqId(Long mrqId) {
		this.mrqId = mrqId;
	}
	public String getContractId() {
		return this.contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}
	public Date getPlanDate() {
		return this.planDate;
	}

	public void setPlanDate(Date planDate) {
		this.planDate = planDate;
	}
	public Date getDelvDate() {
		return this.delvDate;
	}

	public void setDelvDate(Date delvDate) {
		this.delvDate = delvDate;
	}

	public String getReqUser() {
		return this.reqUser;
	}

	public void setReqUser(String reqUser) {
		this.reqUser = reqUser;
	}
	
	public String getContactUser() {
		return this.contactUser;
	}

	public void setContactUser(String contactUser) {
		this.contactUser = contactUser;
	}
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}
	public String getDelvAddr() {
			return this.delvAddr;
		}

	public void setDelvAddr(String delvAddr) {
			this.delvAddr = delvAddr;
		}
	public String getRemark() {
			return this.remark;
		}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	

	public MtrRequestDetail[] getMrds() {
		return this.mrds;
	}

	public void setMrds(MtrRequestDetail[] mrds) {
		this.mrds = mrds;
	}
}